// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/agents" | "/admin/categories" | "/admin/categories/[id]" | "/admin/categories/new" | "/admin/dashboard" | "/admin/leads" | "/admin/posts" | "/admin/posts/[id]" | "/admin/posts/new" | "/admin/settings" | "/admin/testimonials" | "/admin/testimonials/[id]" | "/admin/testimonials/new" | "/ai" | "/ai-hub" | "/auth/auth-code-error" | "/automation" | "/blog" | "/blog/[category]" | "/blog/[category]/[slug]" | "/design" | "/hosting" | "/login" | "/marketing" | "/systems" | "/systems/api" | "/systems/custom" | "/web" | "/web/custom" | "/web/ecommerce" | "/web/layouts"
type AppRouteHandlerRoutes = "/api/ai/generate-seo" | "/api/chat/[agentId]" | "/api/generate-post" | "/api/leads" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/ai-hub"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/agents": {}
  "/admin/categories": {}
  "/admin/categories/[id]": { "id": string; }
  "/admin/categories/new": {}
  "/admin/dashboard": {}
  "/admin/leads": {}
  "/admin/posts": {}
  "/admin/posts/[id]": { "id": string; }
  "/admin/posts/new": {}
  "/admin/settings": {}
  "/admin/testimonials": {}
  "/admin/testimonials/[id]": { "id": string; }
  "/admin/testimonials/new": {}
  "/ai": {}
  "/ai-hub": {}
  "/api/ai/generate-seo": {}
  "/api/chat/[agentId]": { "agentId": string; }
  "/api/generate-post": {}
  "/api/leads": {}
  "/auth/auth-code-error": {}
  "/auth/callback": {}
  "/automation": {}
  "/blog": {}
  "/blog/[category]": { "category": string; }
  "/blog/[category]/[slug]": { "category": string; "slug": string; }
  "/design": {}
  "/hosting": {}
  "/login": {}
  "/marketing": {}
  "/systems": {}
  "/systems/api": {}
  "/systems/custom": {}
  "/web": {}
  "/web/custom": {}
  "/web/ecommerce": {}
  "/web/layouts": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/ai-hub": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
