var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/chat/[agentId]/route.js")
R.c("server/chunks/[root-of-the-server]__4df63980._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_1d427892.js")
R.c("server/chunks/node_modules_decdbaeb._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_669a44bf._.js")
R.c("server/chunks/node_modules_next_f5199d09._.js")
R.c("server/chunks/_next-internal_server_app_api_chat_[agentId]_route_actions_170994cc.js")
R.m(51567)
module.exports=R.m(51567).exports
